"""add_bookings_table

Revision ID: 04331a21f358
Revises: 723172a80d0e
Create Date: 2026-06-22 14:27:37.372972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '04331a21f358'
down_revision: Union[str, None] = '723172a80d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmhouse_id', sa.Integer(), nullable=False),
    sa.Column('bookie_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', TZDateTime(), nullable=False),
    sa.Column('end_at', TZDateTime(), nullable=False),
    sa.Column('buffer_minutes_snapshot', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_contact', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('expires_at', TZDateTime(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', TZDateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.Column('updated_at', TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookie_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmhouse_id'], ['farmhouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_bookie_id'), ['bookie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_farmhouse_id'), ['farmhouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_farmhouse_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_bookie_id'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
