"""add_activity_logs_table

Revision ID: 285b5dddbf5d
Revises: 5b0dfe00a158
Create Date: 2026-06-22 14:07:48.316631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '285b5dddbf5d'
down_revision: Union[str, None] = '5b0dfe00a158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index('ix_activity_logs_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('ix_activity_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))
        batch_op.drop_index('ix_activity_logs_created_at')
        batch_op.drop_index('ix_activity_logs_actor_id')

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
