"""add_invite_tokens_table

Revision ID: 5b0dfe00a158
Revises: aeb794a20b68
Create Date: 2026-06-22 13:59:31.117369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '5b0dfe00a158'
down_revision: Union[str, None] = 'aeb794a20b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', TZDateTime(), nullable=False),
    sa.Column('used_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_invite_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_invite_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_invite_tokens_id'))

    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
