"""add_policies_table

Revision ID: 723172a80d0e
Revises: 285b5dddbf5d
Create Date: 2026-06-22 14:16:15.119529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '723172a80d0e'
down_revision: Union[str, None] = '285b5dddbf5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.Column('updated_at', TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_id'))

    op.drop_table('policies')
    # ### end Alembic commands ###
