"""add settings and blackout_dates

Revision ID: 7a3f5af40bea
Revises: 9dfe6aed56b4
Create Date: 2026-06-22 16:15:58.256214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '7a3f5af40bea'
down_revision: Union[str, None] = '9dfe6aed56b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hold_duration_hours', sa.Integer(), nullable=False),
    sa.Column('min_advance_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('default_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('operating_hours_start', sa.String(length=5), nullable=True),
    sa.Column('operating_hours_end', sa.String(length=5), nullable=True),
    sa.Column('updated_at', TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blackout_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmhouse_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmhouse_id'], ['farmhouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blackout_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blackout_dates_farmhouse_id'), ['farmhouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blackout_dates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackout_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blackout_dates_id'))
        batch_op.drop_index(batch_op.f('ix_blackout_dates_farmhouse_id'))

    op.drop_table('blackout_dates')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
