"""add booking cancellation fields

Revision ID: 9dfe6aed56b4
Revises: 04331a21f358
Create Date: 2026-06-22 15:48:58.163985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = '9dfe6aed56b4'
down_revision: Union[str, None] = '04331a21f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_requested_at', TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_requested_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_cancel_requested_by_users', 'users', ['cancel_requested_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_cancel_requested_by_users', type_='foreignkey')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancel_requested_by')
        batch_op.drop_column('cancel_requested_at')

    # ### end Alembic commands ###
