"""add farmhouses table

Revision ID: aeb794a20b68
Revises: e6e5787af71c
Create Date: 2026-06-22 13:49:33.376061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db import TZDateTime


# revision identifiers, used by Alembic.
revision: str = 'aeb794a20b68'
down_revision: Union[str, None] = 'e6e5787af71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmhouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.Column('updated_at', TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmhouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmhouses_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmhouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmhouses_id'))

    op.drop_table('farmhouses')
    # ### end Alembic commands ###
